ceph_cluster: ceph
ceph_conf_file: "/etc/ceph/ceph.conf"

mon_group_name: mons
osd_group_name: osds
rgw_group_name: rgws

rgw_pcs_resource: p_ceph_rgw

ceph_common_packages:
  - ceph
  - ceph-common
  - ceph-deploy
  - libcephfs1
  - python-ceph-compat
  - python-cephfs

ceph_lib_packages:
  - librados2
  - librbd1
  - python-rados
  - python-rbd

ceph_rgw_packages:
  - ceph-radosgw

rgw_use_keystone: "false"
keystone_accepted_roles: "Member, _member_, admin, SwiftOperator"
keystone_token_cache_size: "500"
keystone_revocation_interval: "500"
rgw_s3_use_keystone: "true"

ceph_conf:
  - section: "global"
    pre_check: "{{ rgw_use_keystone|bool }}"
    apply_to:
      - "{{ rgw_group_name }}"
    configurations:
      - option: "rgw keystone url"
        value: "{{ rgw_keystone_url|default('') }}"
      - option: "rgw keystone admin token"
        value: "{{ keystone_admin_token|default('') }}"
      - option: "rgw keystone accepted roles"
        value: "{{ keystone_accepted_roles }}"
      - option: "rgw keystone token cache size"
        value: "{{ keystone_token_cache_size }}"
      - option: "rgw keystone revocation interval"
        value: "{{ keystone_revocation_interval }}"
      - option: "rgw s3 auth use keystone"
        value: "{{ rgw_s3_use_keystone }}"
